name: Build Docker Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      file_name:
        required: true
        type: string
      base_image:
        required: true
        type: string
      distro:
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Check last modified time of image in registry
        id: modify_date
        run: |
          echo "image=$(date -d \"$(curl -s https://hub.docker.com/v2/repositories/$(echo ${{ inputs.image_name }} | sed 's/:/\/tags\//')\" | jq -r '.last_updated')\" +%s)" >> $GITHUB_OUTPUT
          echo "dockerfile=$(date -d \"$(git log -n 1 --format=%cd --date=iso -- ${{ inputs.file_name }})\" +%s)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        if: |
          steps.modify_date.outputs.image < steps.modify_date.outputs.dockerfile
        uses: docker/build-push-action@v3
        with:
          tags: ${{ inputs.image_name }}
          file: ${{ inputs.file_name }}
          push: true
          build-args: |
            BASEIMAGE=${{ inputs.base_image }}
            ${{ inputs.distro != '' && format('DISTRO={0}', inputs.distro) || '' }}
