name: deploy
on: push
jobs:
  base_images:
    name: Image ${{ matrix.docker_image.image_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - file_name: "base.dockerfile"
            image_name: "rafa606/ubuntu:18.04"
            base_image: "ubuntu:18.04"
          - file_name: "base.dockerfile"
            image_name: "rafa606/ubuntu:20.04"
            base_image: "ubuntu:20.04"
          - file_name: "base.dockerfile"
            image_name: "rafa606/ubuntu:22.04"
            base_image: "ubuntu:22.04"

    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Check last modified time of Foo Dockerfile
        id: image_modify_date
        run: |
          echo "::set-output name=value::$(date -d "$(docker inspect --format='{{.Created}}' ${{ matrix.docker_image.image_name }})" +%s)"

      - name: Check last modified time of Foo Docker image
        id: file_modify_date
        run: |
          echo "::set-output name=value::$(date -d "$(git log -1 --format=%cd --date=iso -- ${{ matrix.docker_image.file_name }})" +%s)"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push ${{ matrix.docker_image.image_name }}
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.docker_image.image_name }}
          file: ${{ matrix.docker_image.file_name }}
          push: true
          build-args: |
            BASEIMAGE=${{ matrix.docker_image.base_image }}
        if: |
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.value

  build_cpp:
    needs: base_images
    name: Image ${{ matrix.docker_image.image_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - file_name: "cpp_vim.dockerfile"
            base_image: "rafa606/ubuntu:18.04"
            image_name: "rafa606/cpp-vim:28.04"
          - file_name: "cpp_vim.dockerfile"
            base_image: "rafa606/ubuntu:20.04"
            image_name: "rafa606/cpp-vim:20.04"
          - file_name: "cpp_vim.dockerfile"
            base_image: "rafa606/ubuntu:22.04"
            image_name: "rafa606/cpp-vim:22.04"

    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Check last modified time of Foo Dockerfile
        id: image_modify_date
        run: |
          echo "::set-output name=value::$(date -d "$(docker inspect --format='{{.Created}}' ${{ matrix.docker_image.image_name }})" +%s)"

      - name: Check last modified time of Foo Docker image
        id: file_modify_date
        run: |
          echo "::set-output name=dockerfile::$(date -d "$(git log -1 --format=%cd --date=iso -- ${{ matrix.docker_image.file_name }})" +%s)"
          echo "::set-output name=vimrc::$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/vimrc)" +%s)"
          echo "::set-output name=ycm::$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/ycm_extra_conf.py)" +%s)"
          echo "::set-output name=ctags::$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/ctags)" +%s)"
          echo "::set-output name=gdbinit::$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/gdbinit)" +%s)"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push ${{ matrix.docker_image.image_name }}
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.docker_image.image_name }}
          file: ${{ matrix.docker_image.file_name }}
          push: true
          build-args: |
            BASEIMAGE=${{ matrix.docker_image.base_image }}
            ROSDISTRO=${{ matrix.docker_image.ros }}
        if: |
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.Dockerfile ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.vimrc ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.ycm ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.ctags ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.gdbinit
