name: deploy
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: build and push to doker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repostory: ${{ github.repostory }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
          load: true
          context: .
          file: latex.dockerfile
