name: deploy
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push to docker vim with latex
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/vim-with-latex
          file: latex.dockerfile
          push: true
      - name: build and push ros noetic with vim image
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros_noetic_vim
          file: ros_noetic_vim.dockerfile
          push: true
      - name: build and push ros noetic with vim and latex image
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros-noetic-vim-latex
          file: ros_noetic_vim_latex.dockerfile
          push: true
