name: deploy
on: push
jobs:
  deploy_latex:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v34.1.1

      - name: build and push to docker vim with latex
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/vim-with-latex
          file: latex.dockerfile
          push: true
        if: |
          contains(steps.changed-files.outputs.modified_files, 'latex.dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'configfiles/vimrc_latex')

  deploy_ros:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - file_name: "cpp_vim.dockerfile"
            image_name: "rafa606/ros-noetic-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros.py"
            ros: "noetic"
            base_image: "ros:noetic-ros-base"

          - file_name: "cpp_vim.dockerfile"
            image_name: "rafa606/ros-melodic-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros.py"
            ros: "melodic"
            base_image: "ros:melodic-ros-base"

          - file_name: "moveit_noetic_source.dockerfile"
            image_name: "rafa606/ros-moveit-noetic-source-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros.py"
            ros: ""

          - file_name: "moveit_noetic_release.dockerfile"
            image_name: "rafa606/ros-moveit-noetic-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros.py"
            ros: ""

          - file_name: "moveit_melodic_release.dockerfile"
            image_name: "rafa606/ros-moveit-melodic-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros.py"
            ros: ""

          - file_name: "ros_foxy_vim.dockerfile"
            image_name: "rafa606/ros-foxy-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros2.py"
            ros: ""

          - file_name: "ros_galactic_vim.dockerfile"
            image_name: "rafa606/ros-galactic-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros2.py"
            ros: ""

          - file_name: "ros_humble_vim.dockerfile"
            image_name: "rafa606/ros-humble-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros2.py"
            ros: ""

          - file_name: "cpp_vim.dockerfile"
            image_name: "rafa606/cpp-vim"
            ycm_file: "configfiles/ycm_extra_conf.py"
            base_image: "ubuntu:22.04"
            ros: ""

          - file_name: "cpp_vim.dockerfile"
            image_name: "rafa606/cpp-vim:ubuntu20.04"
            ycm_file: "configfiles/ycm_extra_conf.py"
            base_image: "ubuntu:20.04"
            ros: ""

          - file_name: "cpp_vim.dockerfile"
            image_name: "rafa606/cpp-vim:ubuntu18.04"
            ycm_file: "configfiles/ycm_extra_conf.py"
            base_image: "ubuntu:18.04"
            ros: ""

          - file_name: "moveit_humble_release.dockerfile"
            image_name: "rafa606/ros-moveit-humble-vim"
            ycm_file: "configfiles/ycm_extra_conf_ros2.py"
            ros: ""
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v34.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push ${{ matrix.docker_image.image_name }}
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.docker_image.image_name }}
          file: ${{ matrix.docker_image.file_name }}
          push: true
          build-args: |
            BASEIMAGE=${{ matrix.docker_image.base_image }}
            ROSDISTRO=${{ matrix.docker_image.ros }}
        if: |
          contains(steps.changed-files.outputs.modified_files, ${{ matrix.docker_image.file_name }}) ||
          contains(steps.changed-files.outputs.modified_files, 'configfiles/vimrc') ||
          contains(steps.changed-files.outputs.modified_files, ${{ matrix.docker_image.ycm_file }}) ||
          contains(steps.changed-files.outputs.modified_files, 'configfiles/ctags')
