name: deploy
on: push
jobs:
  base_images:
    name: Image ${{ matrix.docker_image.image_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - file_name: "base.dockerfile"
            image_name: "rafa606/ubuntu:18.04"
            base_image: "ubuntu:18.04"
          - file_name: "base.dockerfile"
            image_name: "rafa606/ubuntu:20.04"
            base_image: "ubuntu:20.04"
          - file_name: "base.dockerfile"
            image_name: "rafa606/ubuntu:22.04"
            base_image: "ubuntu:22.04"

    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0" #<<< important to get correct dates

      - name: Check last modified time of the image of registry
        id: image_modify_date
        run: |
          if docker pull ${{ matrix.docker_image.image_name }}; then \
            echo "value=$(date -d "$(docker inspect --format='{{.Created}}' ${{ matrix.docker_image.image_name }})" +%s)" >> $GITHUB_OUTPUT; \
          fi

      - name: Check last modified time of Dockerfile
        id: file_modify_date
        run: |
          echo "value=$(date -d "$(git log -n 1 --format=%cd --date=iso -- ${{ matrix.docker_image.file_name }})" +%s)" >> $GITHUB_OUTPUT
      - name: Test
        id: test
        run: |
          echo "${{ steps.image_modify_date.outputs.value }} < ${{ steps.file_modify_date.outputs.value }}"
          [ 1683613342 -lt 1683539974 ] && echo yes || echo no
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push ${{ matrix.docker_image.image_name }}
        if: |
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.value
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.docker_image.image_name }}
          file: ${{ matrix.docker_image.file_name }}
          push: true
          build-args: |
            BASEIMAGE=${{ matrix.docker_image.base_image }}

  ros_base_images:
    needs: base_images
    name: Image ${{ matrix.docker_image.image_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - file_name: "ros.dockerfile"
            base_image: "rafa606/ubuntu:18.04"
            image_name: "rafa606/ros:melodic"
            ros_distro: "melodic"
          - file_name: "ros.dockerfile"
            base_image: "rafa606/ubuntu:20.04"
            image_name: "rafa606/ros:noetic"
            ros_distro: "noetic"
          - file_name: "ros.dockerfile"
            base_image: "rafa606/ubuntu:22.04"
            image_name: "rafa606/ros:humble"
            ros_distro: "humble"

    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0"

      - name: Check last modified time of Foo Dockerfile
        id: image_modify_date
        run: |
          if docker pull ${{ matrix.docker_image.image_name }}; then \
            echo "value=$(date -d "$(docker inspect --format='{{.Created}}' ${{ matrix.docker_image.image_name }})" +%s)" >> $GITHUB_OUTPUT; \
          fi

      - name: Check last modified time of Foo Docker image
        id: file_modify_date
        run: |
          echo "value=$(date -d "$(git log -1 --format=%cd --date=iso -- ${{ matrix.docker_image.file_name }})" +%s)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push ${{ matrix.docker_image.image_name }}
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.docker_image.image_name }}
          file: ${{ matrix.docker_image.file_name }}
          push: true
          build-args: |
            BASEIMAGE=${{ matrix.docker_image.base_image }}
            DISTRO=${{ matrix.docker_image.ros_distro }}
        if: |
          ${{ steps.image_modify_date.outputs.value }} < ${{ steps.file_modify_date.outputs.value }}

  build_cpp:
    needs: base_images
    name: Image ${{ matrix.docker_image.image_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - file_name: "cpp_vim.dockerfile"
            base_image: "rafa606/ubuntu:18.04"
            image_name: "rafa606/cpp-vim:18.04"
          - file_name: "cpp_vim.dockerfile"
            base_image: "rafa606/ubuntu:20.04"
            image_name: "rafa606/cpp-vim:20.04"
          - file_name: "cpp_vim.dockerfile"
            base_image: "rafa606/ubuntu:22.04"
            image_name: "rafa606/cpp-vim:22.04"

    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0"

      - name: Check last modified time of Foo Dockerfile
        id: image_modify_date
        run: |
          if docker pull ${{ matrix.docker_image.image_name }}; then \
            echo "value=$(date -d "$(docker inspect --format='{{.Created}}' ${{ matrix.docker_image.image_name }})" +%s)" >> $GITHUB_OUTPUT; \
          fi

      - name: Check last modified time of Foo Docker image
        id: file_modify_date
        run: |
          echo "dockerfile=$(date -d "$(git log -1 --format=%cd --date=iso -- ${{ matrix.docker_image.file_name }})" +%s)" >> $GITHUB_OUTPUT
          echo "vimrc=$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/vimrc)" +%s)" >> $GITHUB_OUTPUT
          echo "ycm=$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/ycm_extra_conf.py)" +%s)" >> $GITHUB_OUTPUT
          echo "ctags=$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/ctags)" +%s)" >> $GITHUB_OUTPUT
          echo "gdbinit=$(date -d "$(git log -1 --format=%cd --date=iso -- ./configfiles/gdbinit)" +%s)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push ${{ matrix.docker_image.image_name }}
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.docker_image.image_name }}
          file: ${{ matrix.docker_image.file_name }}
          push: true
          build-args: |
            BASEIMAGE=${{ matrix.docker_image.base_image }}
            ROSDISTRO=${{ matrix.docker_image.ros }}
        if: |
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.Dockerfile ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.vimrc ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.ycm ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.ctags ||
          steps.image_modify_date.outputs.value < steps.file_modify_date.outputs.gdbinit
