name: deploy
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v17.2

      - name: build and push to docker vim with latex
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/vim-with-latex
          file: latex.dockerfile
          push: true
        if: contains(steps.changed-files.outputs.modified_files, 'latex.dockerfile')

      - name: build and push ros noetic with vim image
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros_noetic_vim
          file: ros_noetic_vim.dockerfile
          push: true
        if: contains(steps.changed-files.outputs.modified_files, 'ros_noetic_vim.dockerfile')


      - name: build and push ros moveit noetic with vim image
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros_moveit_noetic_source_vim
          file: ros_noetic_vim.dockerfile
          push: true
        if: contains(steps.changed-files.outputs.modified_files, 'moveit_noetic_source.dockerfile')

      - name: build and push ros galactic with vim image
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros-base-galactic-vim
          file: ros_galactic_vim.dockerfile
          push: true
        if: contains(steps.changed-files.outputs.modified_files, 'ros_galactic_vim.dockerfile')

      - name: build and push ros foxy with vim image
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros-base-foxy-vim
          file: ros_galactic_vim.dockerfile
          push: true
        if: contains(steps.changed-files.outputs.modified_files, 'ros_foxy_vim.dockerfile')

      - name: build and push ros noetic with vim and latex image
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/ros-noetic-vim-latex
          file: ros_noetic_vim_latex.dockerfile
          push: true
        if: contains(steps.changed-files.outputs.modified_files, 'ros_noetic_vim_latex.dockerfile')
